[deps]
Catlab = "134e5e36-593f-5add-ad60-77f754baafbe"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Librsvg_jll = "925c91fb-5dd6-59dd-8e8c-345e74382d89"
Luxor = "ae8d54c2-7ccd-5906-9d76-62fc9837b5bc"
MathTeXEngine = "0a4f8689-d25c-4efe-a92b-7142dfc1aa53"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
